movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),    
]

pjt05/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls'))
]

movies/models.py
from django.db import models

class Movie(models.Model):
    title = models.CharField(max_length=100)
    overview = models.TextField()
    poster_path = models.CharField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

movies/forms.py
from django import forms
from . models import Movie

class MovieForm(forms.ModelForm):
    

    class Meta:
        model = Movie
        fields = '__all__'

movies/views.py
from django.core import paginator
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators .http import require_safe, require_POST, require_http_methods
from .models import Movie
from .forms import MovieForm
from django.core.paginator import Paginator


# 전체 목록 조회 페이지 반환
@require_safe
def index(request):
    movies = Movie.objects.order_by('-pk')
    paginator = Paginator(movies, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'movies': movies,
        'page_obj': page_obj,
    }
    return render(request, 'movies/index.html', context)


# POST 요청시 데이터 생성 및 Detail Page로 Redirect, 그 외에는 생성페이지 반환
@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method == 'POST':
        form = MovieForm(request.POST)
        if form.is_valid():
            movie = form.save()
            return redirect('movies:detail', movie.pk)
    else:
        form = MovieForm()
        navbar = 'create'
    context = {
        'form': form,
        'navbar': navbar,
    }
    return render(request, 'movies/create.html', context)


# 상세페이지 반환
@require_safe
def detail(request, pk):
    movie = get_object_or_404(Movie, pk=pk)
    context = {
        'movie': movie,
    }
    return render(request, 'movies/detail.html', context)


# POST 요청시 데이터 수정 및 Detail Page로 Redirect, 그 외에는 수정페이지 반환
@require_http_methods(['GET', 'POST'])
def update(request, pk):
    movie = get_object_or_404(Movie, pk=pk)
    if request.method == 'POST':
        form = MovieForm(request.POST, instance=movie)
        if form.is_valid():
            movie = form.save()
            return redirect('movies:detail', movie.pk)
    else:
        form = MovieForm(instance=movie)
    context = {
        'form': form,
        'movie': movie,
    }
    return render(request, 'movies/update.html', context)


# POST 요청시 데이터 삭제 후 index Page로 Redirect
@require_POST
def delete(request, pk):
    movie = get_object_or_404(Movie, pk=pk)
    movie.delete()
    return redirect('movies:index')

movies/templates/movies/create.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
<form action="" method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  <div class="d-flex justify-content-end">
    <button class="btn btn-danger m-2">SUBMIT</button>
    <a href="{% url 'movies:index' %}">
      <button class="btn btn-secondary">CANCLE</button>
    </a>
  </div>
</form>

{% endblock  %}

movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}

<a href="{% url 'movies:index' %}" class="m-1 text-decoration-none text-secondary">
  <h5 class="">
  <-BACK
  </h5>
</a>
<div class="d-flex">
  <img src="{{ movie.poster_path }}" alt="movie" width="400px">
  <div class="d-flex flex-column container m-3 justify-content-between">
    <div>
      <h1 class="mb-3 ms-3">{{ movie.title }}</h1>
      <p class="mb-1 text-secondary ms-3">Created at : {{ movie.created_at }}</p>
      <p class="mb-4 text-secondary ms-3">Updated at : {{ movie.updated_at }}</p>
      <div class="bg-light p-4 rounded-3">
        <p>{{ movie.overview|linebreaksbr }}</p>
      </div>
    </div>
    <div class="d-flex justify-content-end mt-5">
      <a href="{% url 'movies:update' movie.pk %}" class="m-1">
        <button class="btn btn-danger">EDIT</button>
      </a>
      <form action="{% url 'movies:delete' movie.pk %}" method="POST" class="m-1">
        {% csrf_token %}
        <button class="btn btn-secondary">DELETE</button>
      </form>
    </div>
  </div>
</div>

{% endblock  %}

movies/templates/movies/index.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block css %}
  <style>
  .card-body .card-text {
    overflow: hidden;
    text-overflow: ellipsis;
    height: 75px;
    display:-webkit-box; 
    word-wrap:break-word; 
    -webkit-line-clamp:3; 
    -webkit-box-orient:vertical; 
  }
  .pagination > li > a
  {
      background-color: white;
      color: #5A4181;
  }

  .pagination > li > a:focus,
  .pagination > li > a:hover,
  .pagination > li > span:focus,
  .pagination > li > span:hover
  {
      color: #5a5a5a;
      background-color: #eee;
      border-color: #ddd;
  }

  .pagination > .active > a
  {
      color: white;
      background-color: #CD5C5C !Important;
      border: solid 1px #CD5C5C !Important;
  }

  .pagination > .active > a:hover
  {
      background-color: #CD5C5C !Important;
      border: solid 1px #CD5C5C;
  }
  </style>

{% endblock  %}
{% block content %}

<div class="row row-cols-1 row-cols-md-3 g-4">
  {% for movie in page_obj %}
    <div class="col">
      <div class="card">
        <a href="{% url 'movies:detail' movie.pk %}">
          <img src="{{ movie.poster_path }}" class="card-img-top" alt="{{ movie.title }}">
        </a>
        <a href="{% url 'movies:detail' movie.pk %}" class="text-decoration-none text-dark">
          <div class="card-body" height="100px">
            <h4 class="card-title">{{ movie.title }}</h4>
            <p class="card-text text-secondary">{{ movie.overview }}</p>
          </div>
        </a>
      </div>
    </div>
  {% endfor %}
</div>

<div class="d-flex justify-content-center m-5">
  {% bootstrap_pagination page_obj %} 
</div>

{% endblock  %}



{% comment %} <div class="row row-cols-1 row-cols-md-3 g-4">
{% for movie in page_obj %}
  <div class="col">
    <div class="card">
      <img src="{{ movie.poster_path }}" class="card-img-top" alt="{{ movie.title }}">
      <div class="card-body">
        <h5 class="card-title">{{ movie.title }}</h5>
        <p class="card-text">{{ movie.overview }}</p>
      </div>
    </div>
  </div>
{% endfor %}




<div class="row row-cols-1 row-cols-md-3 g-4">
  <div class="col">
    <div class="card">
      <img src="..." class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
      <img src="..." class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
      <img src="..." class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content.</p>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
      <img src="..." class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
    </div>
  </div>
</div> {% endcomment %}

movies/templates/movies/update.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <div class="d-flex justify-content-end">
      <button class="btn btn-danger m-2">SUBMIT</button>
      <a href="{% url 'movies:detail' movie.pk %}">
        <button class="btn btn-secondary m-2">CANCLE</button>
      </a>
    </div>
  </form>
{% endblock  %}

templates/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'movies:index' %}"><h1 class="ms-2 text-danger fw-bold" style="font-family: 'Allison', cursive;">Movies</h1></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        {% if navbar %}
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'movies:index' %}"><h5>HOME</h5></a>
          </li>
          <li class="nav-item">
            <a class="nav-link active text-danger" href="{% url 'movies:create' %}"><h5>CREATE</h5></a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link active text-danger" aria-current="page" href="{% url 'movies:index' %}"><h5>HOME</h5></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'movies:create' %}"><h5>CREATE</h5></a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>
<br><br>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Allison&family=Cairo&family=Quicksand:wght@300&display=swap" rel="stylesheet">
  {% block css %}{% endblock  %}
  <style>
  * {
    font-family: 'Cairo', sans-serif;
  }
  </style>
  <title>MOVIES</title>
</head>
<body>
  {% include '_navbar.html' %}
  
  <div class="container">
  {% block content %}{% endblock  %}
  </div>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>